FROM nwodtuhs/exegol:full-3.1.6

# Installer dépendances
RUN apt-get update && \
    apt-get install -y \
    git curl autoconf build-essential libpcap-dev \
    libsqlite3-dev libpq-dev postgresql \
    libreadline-dev libssl-dev zlib1g-dev libyaml-dev \
    ruby-full ruby-dev \
    libgmp-dev libffi-dev nodejs

EXPOSE 5000

# Cloner Metasploit Framework
RUN git clone https://github.com/rapid7/metasploit-framework /opt/metasploit-framework

# Installer les dépendances Ruby
WORKDIR /opt/metasploit-framework
RUN gem install bundler 
COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

RUN mkdir /toolbox
WORKDIR /toolbox
COPY ./requirements.txt .
RUN pip install --break-system-packages -r requirements.txt

# Ajouter au PATH
ENV PATH="/opt/metasploit-framework:$PATH"

ENTRYPOINT [ "/entrypoint.sh" ]
